version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - python_rabbitmq_net
    healthcheck:
        test: rabbitmq-diagnostics -q ping
        interval: 30s
        timeout: 30s
        retries: 3

  sender:
    build: ./sender
    container_name: 'sender'
    volumes:
      - ./sender:/sender
    ports:
      - 8080:5000
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq
    networks:
      - python_rabbitmq_net

  reciever:
    build: ./reciever
    volumes:
      - ./reciever:/reciever
    depends_on:
      rabbitmq:
        condition: service_healthy
    links: 
        - rabbitmq
    networks:
      - python_rabbitmq_net
    deploy:
      mode: replicated
      replicas: 3

networks:
  python_rabbitmq_net:
    driver: bridge